.PHONY: riverpod-setup
riverpod-setup:
	flutter pub add flutter_riverpod
	flutter pub add riverpod_annotation
	flutter pub add build_runner --dev
	flutter pub add riverpod_generator --dev
	flutter pub get

.PHONY: isar-setup
isar-setup:
	flutter pub add isar
	flutter pub add isar_flutter_libs
	flutter pub add path_provider
	flutter pub add build_runner --dev
	flutter pub add isar_generator --dev
	flutter pub get

.PHONY: freezed-setup
freezed-setup:
	flutter pub add freezed_annotation
	flutter pub add build_runner --dev
	flutter pub add freezed --dev
	flutter pub add json_serializable --dev
	flutter pub add json_annotation
	flutter pub get
